# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_immobilier
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml